In [1]:
import numpy as np
import tensorly as tl

In [2]:
a = np.arange(1, 9).reshape((2,2,2))
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [3]:
tl.unfold(a, 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
a = np.arange(1, 28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [26]:
a[0,:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a[:,:,0]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [31]:
tl.unfold(a, 0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [23]:
tl.unfold(a, 1)

array([[ 1,  2,  3, 10, 11, 12, 19, 20, 21],
       [ 4,  5,  6, 13, 14, 15, 22, 23, 24],
       [ 7,  8,  9, 16, 17, 18, 25, 26, 27]])

In [28]:
tl.unfold(a, 2)

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [9]:
a = np.arange(10)
a[0:3]

array([0, 1, 2])

In [12]:
np.diag(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [88]:
a = np.random.uniform(0, 1, (5, 5))
print(a)
b = np.linalg.svd(a, 3)

[[0.1223652  0.51340576 0.37443652 0.44298534 0.82696   ]
 [0.6481303  0.57691622 0.80980305 0.15501181 0.57577838]
 [0.33097278 0.28210615 0.55282072 0.47664939 0.10374515]
 [0.3279378  0.55297838 0.75075093 0.12087779 0.0690007 ]
 [0.72155971 0.67749746 0.70450996 0.97301911 0.37807847]]


In [89]:
b[0] @ np.diag(b[1]) @ b[2]

array([[0.1223652 , 0.51340576, 0.37443652, 0.44298534, 0.82696   ],
       [0.6481303 , 0.57691622, 0.80980305, 0.15501181, 0.57577838],
       [0.33097278, 0.28210615, 0.55282072, 0.47664939, 0.10374515],
       [0.3279378 , 0.55297838, 0.75075093, 0.12087779, 0.0690007 ],
       [0.72155971, 0.67749746, 0.70450996, 0.97301911, 0.37807847]])

In [94]:
np.sum(b[0][:,1] * b[2][1,:])
np.sum(b[2][1, :] * b[2][1, :])
np.sum(b[2][1, :] * b[2][0, :])

1.1102230246251565e-16

In [15]:
np.diagonal(a)

array([0.71166253, 0.44901127, 0.4954989 , 0.72248079, 0.79526844])

In [ ]:
tl.tenalg.

In [ ]:
tl.tenalg.mode_dot

In [ ]:
np.transpose

In [38]:
a = np.arange(-10, 10).reshape((4,5))
np.clip(a, -1, 1)
a.clip(-1, 1, inplace = True)
a

TypeError: 'inplace' is an invalid keyword to ufunc 'clip'

In [95]:
a = np.arange(10).reshape((2, 5))
np.fill_diagonal(a, 0)
a

array([[0, 1, 2, 3, 4],
       [5, 0, 7, 8, 9]])

In [96]:
def hetero_pca_test(Y, r, tmax = 20, vartol = 1e-6):
    N_t = Y.copy()
    r = min(np.min(r), np.min(N_t.shape))
    np.fill_diagonal(N_t, 0)
    U_t = np.zeros((Y.shape[0], r))
    
    t = 1
    approx = -1
    while t < tmax:
        svd_res = np.linalg.svd(N_t)
        U_t = svd_res[0][:, 0:r]
        tilde_N_test_t = svd_res[0][:, 0:r] @ np.diag(svd_res[1][0:r]) @ svd_res[2][0:r, :]
        
        svector = np.diagonal(tilde_N_test_t)
        np.fill_diagonal(N_t, svector)
        
        if abs(np.sum(svector**2) - approx) > vartol:
            t += 1
            approx = np.sum(svector**2)
        else:
            break
    return U_t


def tensor_hetero_pca_test(Y, r):
    p = Y.shape
    d = len(p)
    u_0 = []
    for i in range(d):
        Y_i = tl.unfold(Y, i)
        Y_i_hetero_pca = hetero_pca_test(Y_i @ Y_i.T, r[i])
        u_0.append(Y_i_hetero_pca)
    return u_0


def hetero_pca_estimate(Y, r_hat):
    '''
    Y: tensor
    r_hat: rank hat
    '''
    U_hat = tensor_hetero_pca_test(Y, r_hat)
    
    P_U0 = U_hat[0] @ np.transpose(U_hat[0])
    P_U1 = U_hat[1] @ np.transpose(U_hat[1])
    P_U2 = U_hat[2] @ np.transpose(U_hat[2])
    
    Y_hat = tl.tenalg.mode_dot(Y, P_U0, 0)
    Y_hat = tl.tenalg.mode_dot(Y_hat, P_U1, 1)
    Y_hat = tl.tenalg.mode_dot(Y_hat, P_U2, 2)
    
    return np.clip(Y_hat, 0, 1)


def get_prob_sbm(n, L):
    Pt = np.zeros((n, n, L))
    
    prob = np.arange(2 * L + 1) / (2 * L)
    
    B = n // 4
    for layer in range(L):
        p1 = np.random.uniform(prob[L + layer], prob[L + layer + 1], 1)
        p2 = np.random.uniform(prob[layer], prob[layer + 1], 1)
        P = np.ones((n, n)) * p1
        
        P[1:B, 1:B] = p2
        P[B:(2 * B), B:(2 * B)] = p2
        P[(2 * B):(3 * B), (2 * B):(3 * B)] = p2
        P[(3 * B):(4 * B), (3 * B):(4 * B)] = p2
        
        Pt[:, :, layer] = P
    
    return Pt


def get_2prob_sbm(n, L):
    P1 = np.zeros((n, n, L))
    P2 = np.zeros((n, n, L))
    
    prob = np.arange(2 * L + 1) / (2 * L)
    
    B = n // 4
    for layer in range(L):
        p1 = np.random.uniform(prob[L + layer], prob[L + layer + 1], 1)
        p2 = np.random.uniform(prob[layer], prob[layer + 1], 1)
        P = np.ones((n, n)) * p1
        
        P[1:B, 1:B] = p2
        P[B:(2 * B), B:(2 * B)] = p2
        P[(2 * B):(3 * B), (2 * B):(3 * B)] = p2
        P[(3 * B):(4 * B), (3 * B):(4 * B)] = p2
        
        P1[:, :, layer] = P
        P2[:, :, L - layer - 1] = P
    
    return P1, P2


def generate_tensor_probability(n, L, P):
    A = np.zeros((n, n, L))
    for layer in range(L):
        u = np.random.uniform(0, 1, n**2).reshape((n, n))
        A[:, :, layer] = (u < P[:, :, layer]) * 1
    
    r_hat = np.array([10, 10, 10])
    
    return A, r_hat


def frobenius(X):
    return np.sum(X**2)**0.5


In [57]:
frobenius(np.arange(10).reshape((2,5)))

285

In [55]:
np.random.seed(0)

In [222]:
n = 50
L = 20

P = get_prob_sbm(n, L)
A, r_hat = generate_tensor_probability(n, L, P)

P_hat = hetero_pca_estimate(A, r_hat)

error = frobenius(P_hat - P)
print("error: ", error)

error:  14.068647931364312
